# FACE ENCODING SIZE
FACE_ENCODING_SIZE = (40, 40)

# KEEPS ASPECT RATIO
INPUT_HEIGHT = 400.0

# FACE CLASSIFICATION SIZE
MIN_FACE_PREDICT_SIZE = (40, 40)
UNKNOWN_LABEL = "UNKNOWN"
FACE_CONFIDENCE = .9
DEFAULT_THRESHOLDS = [0.6, 0.9]
ALLOWED_IMAGE_TYPES = ('*.jpeg', '*.png', '*.jpg')
